$( document ).ready(function() {
    $('#menu_on').click(function(){ // Al hacer click...
       $('#wrapper').toggleClass('visible_menu'); // Añadimos o eliminamos la clase 'visible_menu' al body
     })
     $('#detail-pizza').click(function(){ // Al hacer click...
       $('#wrapper').toggleClass('visible_menu'); // Añadimos o eliminamos la clase 'visible_menu' al body
     })
     $('#detail-burger').click(function(){ // Al hacer click...
       $('#wrapper').toggleClass('visible_menu'); // Añadimos o eliminamos la clase 'visible_menu' al body
     })
     $('#detail-empanada').click(function(){ // Al hacer click...
       $('#wrapper').toggleClass('visible_menu'); // Añadimos o eliminamos la clase 'visible_menu' al body
     })
     $('#detail-papas').click(function(){ // Al hacer click...
       $('#wrapper').toggleClass('visible_menu'); // Añadimos o eliminamos la clase 'visible_menu' al body
     })
     $('#detail-cajitafeliz').click(function(){ // Al hacer click...
       $('#wrapper').toggleClass('visible_menu'); // Añadimos o eliminamos la clase 'visible_menu' al body
     })
     $('#detail-viandas').click(function(){ // Al hacer click...
        $('#wrapper').toggleClass('visible_menu'); // Añadimos o eliminamos la clase 'visible_menu' al body
      })
    $('#detail-contacto').click(function(){ // Al hacer click...
        $('#wrapper').toggleClass('visible_menu'); // Añadimos o eliminamos la clase 'visible_menu' al body
      })
});